"""Harness contract for e01: vector add. Do not edit this file.

This defines WHAT counts as correct and how we measure you. Your job is
entirely in kernel.py.
"""
import torch

TITLE = "Vector add (your first Triton kernel)"
ENTRYPOINT = "vector_add"   # the function the runner calls in kernel.py
METRIC = "bandwidth"        # this kernel is memory-bound: 2 reads + 1 write
TOL = {"atol": 0.0, "rtol": 0.0}   # plain fp32 add should match torch exactly

N = 1 << 24   # ~16.7M elements


def make_inputs():
    torch.manual_seed(0)
    a = torch.randn(N, device="cuda", dtype=torch.float32)
    b = torch.randn(N, device="cuda", dtype=torch.float32)
    return a, b


def reference(a, b):
    return a + b


def bytes_moved(a, b):
    # read a, read b, write out -> 3 buffers of N float32s
    return 3 * a.numel() * a.element_size()
